### PR TITLE
Rename onewire_demo.py to onewire_simpletest.py

### PR DESCRIPTION
**Pull request by sreekaransrinath**
Fixed issue #12

### CODE REVIEW

**Comment by ladyada** [comment]
thanks for the PR! "/docs/examples.rst" will also need fixing

**Comment by sreekaransrinath** [comment]
Whoops! Missed that,my bad. Fixed it in a separate PR :)

**Comment by kattni** [comment]
@sreekaran16 Thanks for doing this! Apologies for forgetting to mention that in the issue in the first place, I've updated it since. 

I need you to fix it in this PR. The checks are failing because examples.rst hasn't been updated. If I merge it in a separate PR, it will result in merge conflict and the checks still won't pass.

**Comment by sreekaransrinath** [comment]
@kattni It's all good, I hope I've done it properly now :)

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
thanks!

**Pull request merged**
